#ifndef EGOISTICOS_KBENCODER_H
#define EGOISTICOS_KBENCODER_H

#include <stdint.h>
#include <stdbool.h>

#define KEYBOARD_ENCODER_COMMAND_LED_SETTING 0xed
#define KEYBOARD_ENCODER_COMMAND_ECHO 0xee
#define KEYBOARD_ENCODER_COMMAND_SCAN_CODE_SETTING 0xf0
#define KEYBOARD_ENCODER_COMMAND_SCAN_CODE_ACQUISITION 0xf0
#define KEYBOARD_ENCODER_COMMAND_KEYBOARD_ID_ACQUISITION 0xf2
#define KEYBOARD_ENCODER_COMMAND_TYPEMATIC_SETTING 0xf3
#define KEYBOARD_ENCODER_COMMAND_ENABLE_KEYBOARD 0xf4
#define KEYBOARD_ENCODER_COMMAND_DISABLE_KEYBOARD 0xf5
#define KEYBOARD_ENCODER_COMMAND_REQUEST_RESEND 0xfe
#define KEYBOARD_ENCODER_COMMAND_SELF_TEST 0xff

#define KEYBOARD_LED_SETTING_OFF 0U
#define KEYBOARD_LED_SETTING_SCROLL_LOCK 0x01U
#define KEYBOARD_LED_SETTING_NUM_LOCK 0x02U
#define KEYBOARD_LED_SETTING_CAPS_LOCK 0x04U

uint8_t read_keyboard_encoder_buffer();

void write_keyboard_encoder_command(uint8_t command);

uint8_t set_keyboard_led(uint8_t led);

#endif //EGOISTICOS_KBENCODER_H
